name: Android CI

on:
  push:
    branches: [ develop, main, 'release/**' ]
    paths:
      - 'mobile-android/**'
      - 'mobile-android/**/**'
      - '**/*.gradle*'
      - 'gradle/**'
  pull_request:
    branches: [ develop, main, 'release/**' ]
    paths:
      - 'mobile-android/**'
      - '**/*.gradle*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Skip if no Android project
        run: |
          if [ ! -d "mobile-android" ]; then
            echo "No Android project detected in mobile-android/ -> skipping job."
            exit 0
          fi

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build Debug APK
        run: |
          cd mobile-android
          ./gradlew assembleDebug

      - name: Run unit tests
        run: |
          cd mobile-android
          ./gradlew testDebugUnitTest
