name: Android CI

on:
  push:
    branches: [ develop, main, 'release/**' ]
    paths:
      - 'mobile-android/**'
      - 'mobile-android/**/**'
      - '**/*.gradle*'
      - 'gradle/**'
  pull_request:
    branches: [ develop, main, 'release/**' ]
    paths:
      - 'mobile-android/**'
      - '**/*.gradle*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect Android project directory
        id: detect
        run: |
          # Prefer explicit subfolder if it exists
          if [ -d "mobile-android/AndandoAndo_App" ]; then
            echo "project_dir=mobile-android/AndandoAndo_App" >> $GITHUB_ENV
          elif [ -d "mobile-android" ] && (ls mobile-android | grep -q "app\|build.gradle\|settings.gradle" 2>/dev/null); then
            echo "project_dir=mobile-android" >> $GITHUB_ENV
          else
            echo "project_dir=" >> $GITHUB_ENV
          fi
          echo "Detected project dir: $project_dir"
      - name: Abort if no Android project found
        if: ${{ env.project_dir == '' }}
        run: |
          echo "No Android project found under mobile-android. Skipping job."
          exit 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-cache

      - name: Build Debug APK
        run: |
          cd ${{ env.project_dir }}
          chmod +x ./gradlew || true
          ./gradlew assembleDebug

      - name: Run unit tests
        run: |
          cd ${{ env.project_dir }}
          chmod +x ./gradlew || true
          ./gradlew testDebugUnitTest
