name: Backend CI (Build & Test)
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/global.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: |
          cd services/auth-service-dotnet
          dotnet restore

      - name: Build
        run: |
          cd services/auth-service-dotnet
          dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: |
          cd services/auth-service-dotnet
          dotnet test --configuration Release --no-build --verbosity normal

  publish-artifact:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'
      - name: Publish artifact (build output)
        run: |
          cd services/auth-service-dotnet
          dotnet publish -c Release -o publish
      - name: Upload artifact to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: auth-service-publish
          path: services/auth-service-dotnet/publish
