name: Backend CI & Deploy
on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore and Build
        run: |
          cd services/auth-service-dotnet
          dotnet restore
          dotnet build --configuration Release
      - name: Run tests
        run: |
          cd services/auth-service-dotnet
          dotnet test --no-build --verbosity normal

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    # Sólo ejecuto deploy si estamos en develop|main y los secrets existen:
    if: ${{ (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main') && secrets.ZOOMIE_SFTP_HOST && secrets.ZOOMIE_SFTP_USER && secrets.ZOOMIE_SFTP_PASS }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish artifact
        run: |
          cd services/auth-service-dotnet
          dotnet publish -c Release -o publish
      - name: Deploy to Zoomie (SFTP example)
        uses: SamKirkland/FTP-Deploy-Action@4.4.0
        with:
          server: ${{ secrets.ZOOMIE_SFTP_HOST }}
          username: ${{ secrets.ZOOMIE_SFTP_USER }}
          password: ${{ secrets.ZOOMIE_SFTP_PASS }}
          local-dir: services/auth-service-dotnet/publish
          server-dir: /var/www/miapp
